### PR TITLE
Update ember-cli and keen.js, and some new goodies

### PR DESCRIPTION
**Pull request by Ramblurr**
Hi there!

Here's some updates for the library:
- Added a [CHANGELOG.md](CHANGELOG.md)
- Added docs to the KeenQueryingService
- New `.collectionsAll()` method to fetch all event collections
- New `.collection()` method to fetch a single event collections
- Updated to keen.js 3.4.0
- Updated to ember-cli 2.3.0
- Spruced up the README

### CODE REVIEW

**Comment by ksin** [comment]
Hi @Ramblurr! Thanks a lot for the work. I actually don't have maintainer access for this organization anymore. When I find the time, I'll point npm to another repo and we can merge it there. Sorry for any inconvenience.

**Comment by ksin** [comment]
@Ramblurr - Actually, I was just granted access. Will review this soon.

**Comment by Ramblurr** [comment]
Great, thanks @ksin! Think we can have a release soon?

**Comment by ksin** [comment]
Done! Thanks again for everything.

**Pull request merged**
